### PR TITLE
Dockerize And deploy to prod-sc

### PR DESCRIPTION
**Pull request by mikebell90**
This seems to work pretty well. Haven't switched cnames/fd rules yet.

### CODE REVIEW

**Comment by mikebell90** [comment]
Running on prod-sc right now!

**Comment by mikebell90** [comment]
Since I checked in a lot of files (because I don't see the bower_components updated often, let me simplify

./build - builds the docker
/deploy/config is the singularity configs
./Dockerfile is the docker file
/scripts contains the nginx conf and the bootstrap scripts.

**Comment by pennello** [comment]
screen shot 2018-07-05 at 4 07 36 pm

😳

**Comment by pennello** [comment]
With so many files changed, this is a pretty unreadable PR.  Can you please restructure the commits so this is reviewable?

**Comment by mikebell90** [comment]
Actually exactly 5 files changed, but I take your point.

**Pull request closed without merging**
